### ISSUE TITLE
Update FAQ

### ISSUE THREAD

**Issue by Putr** [Pirate-Parties-International/PPI-rest-api#26]
The old FAQ is published, but should be extensively changed as the scope has changed (from an API to a registry).

**Comment by collentine** [comment]
@Putr looked through it and don't see that many changes to make. Only thing is changing API to Registry in most places.

I'm a bit unclear on the differences between an API and a registry. Mind explaining how the scope changes between them?

p.s. there's an advantage to brand it as the Pirate API since we get the name PAPI which will help greatly with spreading it. Pirate Repository (or PREPO) is not as sexy.

**Comment by Putr** [comment]
API is only the machine readable representation of the dataset. 

Registry is the dataset.

Website is the web, human readable representation.

API is the machine readable representation.

Originally (2 years ago) I only planned on giving simple access to the JSON files saved in the github repo. But the scope has continually expanded since than and I think it's only right to name to what it really is - a registry of all pirate parties with and api and web presentation
