### ISSUE TITLE
Image and video postIDs for twitter posts don't exist on twitter

### ISSUE THREAD

**Issue by GuruVII** [Pirate-Parties-International/PPI-rest-api#48]
If you use https://twitter.com/thisCanHaveAnything/status/postID, you should be able to link to every twitter post (example https://twitter.com/ILikePotatoes/status/823506667639898115). 
If I use the IDs in the API, I can link only to twitter posts with the subtype text.
Checking on twitter the postIDs for video and image posts don't match the ones scrapped (you can check by clicking on the arrow in top right corner and clicking copy link to tweet)

Is this a bug or are the scrapped IDs for videos and pictures something other than postIDs and if so, what would be the URL to use the provided IDs to link to them?

**Comment by j-h-s** [comment]
The status ID is stored within the postData array, because at the time I didn't know that it wouldn't be available to the API. And then I just forgot. I've fixed this now so future scrapes will have the right ID.

I also added a patch command, so if you run 'php app/console papi:patch -t' it should go through the db fixing old entries, so you don't need to re-scrape them.

**Comment by j-h-s** [comment]
Also, if you just point to twitter.com/statuses/[postId] it should take you straight there without needing to enter the account it came from.

**Comment by j-h-s** [comment]
Fixed by most recent deployment.
