### ISSUE TITLE
Social media pics/posts filter fixes

### ISSUE THREAD

**Issue by Putr** [Pirate-Parties-International/PPI-rest-api#64]
We need:
- [x] filter by time (last week, month, year)
- [x] filter by engagment (most/least engaged)

alongside the exsisting party and platform

@GuruVII

**Comment by GuruVII** [comment]
@j-h-s  Hi, I think I need to pass the baton for this to you, at least for one of them.
I know I can't make the filter by engagement on my own, because the current one only shows engagement in descending order.
The filter by time, I can do solely on front-end, but it would be more elegant, if it was done on backend and the frontend just called the API.

**Comment by j-h-s** [comment]
Yeah, sure. I was planning on adding both of these options eventually, anyway.

**Comment by Putr** [comment]
More than just more elegant, it would be more efficient. No need to burden
the (slow) client with so much data.

**Comment by j-h-s** [comment]
I've added the direction filter to the master branch, I'll work on adding the time filter later.

**Comment by j-h-s** [comment]
I've added both options to the api now. Sorry it took me so long.

**Comment by j-h-s** [comment]
These changes have been deployed, and they work locally on the master branch, but aren't showing up for me on the live site.

**Comment by j-h-s** [comment]
Never mind. I just deployed the latest change, and it's working now.
